Fix NPL:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.wifi.WifiSetupActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2324)
    at android.app.ActivityThread.access$600(ActivityThread.java:139)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1295)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5117)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.NullPointerException
    at com.android.settings.wifi.WifiSettings.onActivityCreated(WifiSettings.java:251)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:848)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
    at android.app.BackStackRecord.run(BackStackRecord.java:635)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
    at android.app.Activity.performStart(Activity.java:5017)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
    ... 11 more

The WifiSettings fragment will be used in two activity:
Settings$WifiSettingsActivity and WifiSetupActivity, the 2nd one do not
have ActionBar. So need to check the existance of ActionBar before using it.

Change-Id: Ia0d44570492c193c377530f8ab5eafdf6bf9b249